version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
<<<<<<< HEAD
    working_directory: ~/SecretPorject
    steps:
      - checkout
      -run:
        name: Debug location
        command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore SecretProject
      - run:
          name: Build all projects in solution
          command: dotnet build SecretProject
      # - run:
      #     name: Run tests in test project
      #     command: dotnet test Lesson08/StartOfLesson/BaseProject.Test/BaseProject.Test.csproj
=======
    working_directory: ~/Final/SecretProject
    steps:
      - checkout
      - run: 
          name: Debug Location
          command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore 
      - run:
          name: Build all projects in solution
          command: dotnet build
     # - run:
     #    name: Run tests in test project
     #   command: dotnet test GroupProject/
>>>>>>> ab4bd923d16912870091ebf1cb1432ef2513143e
