version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/SecretProject
    steps:
      - checkout
      - run:
          name: Debug location
          command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore GroupApp   
      - run:
          name: Build all projects in solution
          command: dotnet build GroupApp
    
