version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/GroupProject/SecretProject
    steps:
      - checkout
      - run: 
          name: Debug Location
          command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore 
      - run:
          name: Build all projects in solution
          command: dotnet build 
     # - run:
     #    name: Run tests in test project
     #   command: dotnet test GroupProject/